version: '3'

services:
  # Gateway
  leare-gateway:
    build:
      context: .
      # dockerfile: Dockerfile.production
      dockerfile: Dockerfile.dev
    ports:
      - "5555:5555"
    volumes:
      - ./logs:/logs
      - .:/app #SOLO PARA DEV
    networks:
      - leare-network
  # chat_ms

  chat-db:
    image: mongo:7.0
    volumes:
      - ../db/leare_chat_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - leare-network

  chat-web:
    build:
      context: ../leare_chat_ms
      # dockerfile: Dockerfile
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
    depends_on:
      - chat-db
    networks:
      - leare-network

  # ws
  ws:
    build:
      context: ../leare_ws
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      CHAT_MS_URL: "http://chat-web:3002"
    depends_on:
      - chat-web
    networks:
      - leare-network

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local


networks:
  leare-network:
    driver: bridge
