version: '3.8'

services:
  # Gateway
  leare-gateway:
    build:
      context: .
      # dockerfile: Dockerfile.production
      dockerfile: Dockerfile.dev
    ports:
      - "5555:5555"
    volumes:
      - ./logs:/logs
      - .:/app #SOLO PARA DEV
    networks:
      - leare-network
      
  # courses_ms
  courses-db:
    image: postgres:16.2-alpine
    container_name: real-courses-db
    volumes:
      - ../db/leare_courses_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_PORT: 5490
    ports:
      - "5490:5490"
    networks:
      - leare-network
    command: -p 5490
    

  courses-web:
    build:
      context: ../leare_courses_ms
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - courses-db
    networks:
      - leare-network


volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local


networks:
  leare-network:
    driver: bridge
