FROM openjdk:21 AS build

# RUN microdnf install -y maven

WORKDIR /app

COPY pom.xml .
COPY src ./src
COPY mvnw .
COPY .mvn ./.mvn

# RUN mvn clean package
RUN ./mvnw clean package

FROM openjdk:21

WORKDIR /usr/app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 5555

CMD ["java", "-jar", "app.jar"]
