version: '3'

services:
  # Gateway
  leare_gateway:
    build:
      context: .
      # dockerfile: Dockerfile.production
      dockerfile: Dockerfile.dev
    ports:
      - "5555:5555"
    volumes:
      - ./logs:/logs
      - .:/app #SOLO PARA DEV
    networks:
      - leare_network
  # auth_ms

  # chat_ms

  chat_db:
    image: mongo:7.0
    volumes:
      - ../db/leare_chat_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - leare_network

  chat_web:
    build:
      context: ../leare_chat_ms
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
    depends_on:
      - chat_db
    networks:
      - leare_network


  # courses_ms
  courses_db:
    image: postgres:16.2-alpine
    volumes:
      - ../db/leare_courses_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5490:5490"
    networks:
      - leare_network
    

  courses_web:
    build:
      context: ../leare_courses_ms
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - courses_db
    networks:
      - leare_network


  #document_ms
  document_rabbit:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: arquisoft
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - leare_network


  document_server:
    build:
      context: ../leare_document_ms
      dockerfile: Dockerfile.server
    ports:
      - "3004:3004"
    volumes:
      - ../leare_document_ms/temp:/temp
      - ../leare_document_ms/logs:/logs
    networks:
      - leare_network

  document_sidecar:
    build:
      context: ../leare_document_ms
      dockerfile: Dockerfile.sidecar
    volumes:
      - ../leare_document_ms/temp:/temp
      - ../leare_document_ms/logs:/logs
    networks:
      - leare_network


  # search_ms

  search_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: search_db
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - leare_network

  search_web:
    build:
      context: ../leare_search_ms
      dockerfile: Dockerfile
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=3005
      - ELASTICSEARCH_URL=http://search_db:9200
      # - ELASTICSEARCH_URL=http://elastic:password@search_db:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=password
    ports:
      - "3005:3005"
    depends_on:
      - search_db
    networks:
      - leare_network

  # ws

  # user_ms
  usersDb:
    image: mariadb
    volumes:
      - ../db/leare_users_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_app_development
    ports:
      - "3307:3307"
    networks:
      - leare_network

  users_web:
    build:
      context: ../leare_users_ms
      dockerfile: Dockerfile
    volumes:
      - ../leare_users_ms:/app
    ports:
      - "3000:3000"
    depends_on:
      - usersDb
    environment:
      DATABASE_URL: mysql2://root:password@usersDb/my_app_development
    networks:
      - leare_network

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local


networks:
  leare_network:
    driver: bridge
