version: '3.8'

services:
# Gateway
  leare-gateway:
    image: northamerica-northeast1-docker.pkg.dev/mystic-tempo-416400/leare/apigateway-leare-gateway:gcp
    ports:
      - "5555:5555"
      - "9010:9010"
    volumes:
      - ./logs:/app/logs
      # - .:/app #SOLO PARA DEV
    networks:
      - leare-network
  # auth_ms

  auth-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    volumes:
      - ../db/leare_auth_db:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123
    mem_limit: 2048m
    networks:
      - leare-network

  auth-web:
    image: northamerica-northeast1-docker.pkg.dev/mystic-tempo-416400/leare/apigateway-auth-web:gcp
    depends_on:
      - auth-db
    networks:
      - leare-network

  # chat_ms

  chat-db:
    image: mongo:7.0
    volumes:
      - ../db/leare_chat_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - leare-network

  chat-web:
    image: northamerica-northeast1-docker.pkg.dev/mystic-tempo-416400/leare/apigateway-chat-web:gcp
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
    depends_on:
      - chat-db
    networks:
      - leare-network


  # courses_ms
  courses-db:
    image: postgres:16.2-alpine
    container_name: real-courses-db
    volumes:
      - ../db/leare_courses_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_PORT: 5490
    networks:
      - leare-network
    command: -p 5490
    

  courses-web:
    image: northamerica-northeast1-docker.pkg.dev/mystic-tempo-416400/leare/apigateway-courses-web:gcp
    depends_on:
      - courses-db
    networks:
      - leare-network


  #document_ms
  document-rabbit:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: arquisoft
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:   
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q check_running"]
      interval: 50s
      timeout: 4s
      retries: 5
      start_period: 3m
    networks:
      - leare-network

  document-db:
    command: "-jar DynamoDBLocal.jar -sharedDb -port 3014"
    image: "amazon/dynamodb-local:latest"
    container_name: document-db
    working_dir: /home/dynamodblocal
    # volumes:
    #   - "../db/leare_document_db:/home/dynamodblocal/shared-local-instance.db:rw"
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' http://localhost:3014 | grep -E '400|200'"]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 40s
    networks:
      - leare-network


  document-server:
    image: northamerica-northeast1-docker.pkg.dev/mystic-tempo-416400/leare/apigateway-document-server:gcp
    volumes:
      - ../leare_document_ms/temp:/temp
      - ../leare_document_ms/logs:/logs
    ports:
      - "3004:3004"
    depends_on:
      document-db:
        condition: service_healthy
    networks:
      - leare-network

  document-sidecar:
    image: northamerica-northeast1-docker.pkg.dev/mystic-tempo-416400/leare/apigateway-document-sidecar:gcp
    volumes:
      - ../leare_document_ms/temp:/temp
      - ../leare_document_ms/logs:/logs
    depends_on:
      document-db:
        condition: service_healthy
      document-rabbit:
        condition: service_healthy
    networks:
      - leare-network


  # search_ms

  search-db:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: search-db
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - leare-network

  search-web:
    image: northamerica-northeast1-docker.pkg.dev/mystic-tempo-416400/leare/apigateway-search-web:gcp
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=3005
      - ELASTICSEARCH_URL=http://search-db:9200
      # - ELASTICSEARCH_URL=http://elastic:password@search-db:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=password
    depends_on:
      - search-db
    networks:
      - leare-network

  # user_ms
  users-db:
    image: mariadb
    volumes:
      - ../db/leare_users_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: my_app_development
      # MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: password
    networks:
      - leare-network

  users-web:
    image: northamerica-northeast1-docker.pkg.dev/mystic-tempo-416400/leare/apigateway-users-web:gcp
    container_name: users-web
    depends_on:
      - users-db
    environment:
      # DATABASE_URL: mysql2://root@users-db/my_app_development
      DATABASE_URL: mysql2://root:password@users-db/my_app_development
    networks:
      - leare-network


  # ws
  ws:
    image: northamerica-northeast1-docker.pkg.dev/mystic-tempo-416400/leare/apigateway-ws:gcp
    ports:
      - "8001:8001"
    environment:
      CHAT_MS_URL: "http://chat-web:3002"
    depends_on:
      - chat-web
    networks:
      - leare-network

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  finalTest:
    driver: local


networks:
  leare-network:
    driver: bridge
