version: '3'

services:
  # Gateway
  leare-gateway:
    build:
      context: .
      # dockerfile: Dockerfile.production
      dockerfile: Dockerfile.dev
    ports:
      - "5555:5555"
    volumes:
      - ./logs:/logs
      - .:/app #SOLO PARA DEV
    networks:
      - leare-network
  # user_ms
  users-db:
    image: mariadb
    volumes:
      - ../db/leare_users_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: my_app_development
      # MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3307"
    networks:
      - leare-network

  users-web:
    build:
      context: ../leare_users_ms
      dockerfile: Dockerfile
    container_name: users-web
    volumes:
      - ../leare_users_ms:/app
    ports:
      - "3000:3000"
    depends_on:
      - users-db
    environment:
      # DATABASE_URL: mysql2://root@users-db/my_app_development
      DATABASE_URL: mysql2://root:password@users-db/my_app_development
    networks:
      - leare-network

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local


networks:
  leare-network:
    driver: bridge
