version: '3.8'

services:
  #MARK: Manager
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - target: 8080
        published: 8888
        protocol: tcp
        mode: ingress
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - node.role == manager
    hostname: visualizer
    networks:
      - leare-network

# Gateway
  leare-gateway:
    image: northamerica-northeast1-docker.pkg.dev/mystic-tempo-416400/leare/apigateway-leare-gateway:gcp
    ports:
      - target: 5555
        published: 5555
        protocol: tcp
        mode: ingress
    volumes:
      - gateway_logs:/app/logs
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.rack == leare-gateway
          - node.role == manager
    hostname: leare-gateway
    networks:
      - leare-network
 
 #MARK: leare-db

  # courses_ms
  courses-db:
    image: postgres:16.2-alpine
    volumes:
      - courses_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_PORT=5490
    command: -p 5490
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.rack == leare-db
    ports:
      - target: 5490
        published: 5490
        protocol: tcp
        mode: ingress
    hostname: courses-db
    networks:
      - leare-network


 #MARK: leare-ms
  
  # courses_ms
  courses-web:
    image: northamerica-northeast1-docker.pkg.dev/mystic-tempo-416400/leare/apigateway-courses-web:gcp
    depends_on:
      - courses-db
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.rack == leare-ms
    ports:
      - target: 3003
        published: 3003
        protocol: tcp
        mode: ingress
    hostname: courses-web
    networks:
      - leare-network

  

volumes:
  gateway_logs:
    driver: local
  courses_data:
    driver: local  


networks:
  leare-network:
    external: true