apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\david\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe -f docker-compose.yaml convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: auth-db
  name: auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\david\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe -f docker-compose.yaml convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/k8s-leare-network: "true"
        io.kompose.service: auth-db
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: Password123
          image: mcr.microsoft.com/mssql/server:2022-latest
          name: auth-db
          ports:
            - containerPort: 1433
              hostPort: 1433
              protocol: TCP
          resources:
            limits:
              memory: "2147483648"
          volumeMounts:
            - mountPath: /var/opt/mssql/data
              name: auth-db-claim0
      restartPolicy: Always
      volumes:
        - name: auth-db-claim0
          persistentVolumeClaim:
            claimName: auth-db-claim0
status: {}
