apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\david\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe -f docker-compose.yaml convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: chat-web
  name: chat-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chat-web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\david\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe -f docker-compose.yaml convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/k8s-leare-network: "true"
        io.kompose.service: chat-web
    spec:
      containers:
        - env:
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: password
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: root
            - name: ME_CONFIG_MONGODB_URL
              value: mongodb://root:password@mongo:27017/
          image: chat-web
          name: chat-web
          ports:
            - containerPort: 3002
              hostPort: 3002
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
