apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\david\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe -f docker-compose.yaml convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: courses-db
  name: courses-db
spec:
  ports:
    - name: "5490"
      port: 5490
      targetPort: 5490
  selector:
    io.kompose.service: courses-db
status:
  loadBalancer: {}
