apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\david\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe -f docker-compose.yaml convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: users-db
  name: users-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: users-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\david\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe -f docker-compose.yaml convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/k8s-leare-network: "true"
        io.kompose.service: users-db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: my_app_development
            - name: MYSQL_ROOT_PASSWORD
              value: password
          image: mariadb
          name: users-db
          ports:
            - containerPort: 3307
              hostPort: 3307
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: users-db-claim0
      restartPolicy: Always
      volumes:
        - name: users-db-claim0
          persistentVolumeClaim:
            claimName: users-db-claim0
status: {}
