version: '3.8'

services:
  #MARK: Manager
  movil-proxy:
    image: northamerica-northeast1-docker.pkg.dev/mystic-tempo-416400/leare/apigateway-movil-proxy:gcp
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.rack == leare-gateway
          - node.role == manager
    networks:
      - leare-network

# Gateway
  leare-gateway:
    image: northamerica-northeast1-docker.pkg.dev/mystic-tempo-416400/leare/apigateway-leare-gateway:gcp
    ports:
      - target: 5555
        published: 5555
        protocol: tcp
        mode: ingress
    volumes:
      - gateway_logs:/app/logs
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.rack == leare-gateway
          - node.role == manager
    networks:
      - leare-network
 
 #MARK: leare-db

# user_ms
  users-db:
    image: mariadb
    volumes:
      - users_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: my_app_development
      # MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: password
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.rack == leare-db
    networks:
      - leare-network

  # user_ms
  users-web:
    image: northamerica-northeast1-docker.pkg.dev/mystic-tempo-416400/leare/apigateway-users-web:gcp
    depends_on:
      - users-db
    environment:
      # DATABASE_URL: mysql2://root@users-db/my_app_development
      DATABASE_URL: mysql2://root:password@users-db/my_app_development
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.rack == leare-ms
        preferences:
            - spread: node.id
    networks:
      - leare-network


# MARK: volumes  

volumes:
  gateway_logs:
    driver: local
  users_data:
    driver: local
 
networks:
  leare-network:
    driver: overlay