name: Build and Push Images

on:
  push:
    branches:
      # - main
      - actions

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GCP Artifact Registry
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Grant execute permission to mvnw
      run: chmod +x mvnw

    - name: Build and Push Images
      env:
        GCP_REGISTRY: northamerica-northeast1-docker.pkg.dev/mystic-tempo-416400/leare
      run: |
        docker build -f Dockerfile.production -t $GCP_REGISTRY/apigateway-leare-gateway:$GITHUB_SHA .
        docker push $GCP_REGISTRY/apigateway-leare-gateway:$GITHUB_SHA
#        docker compose -f privateDocker-compose.yaml build
#        docker tag apigateway-leare-gateway northamerica-northeast1-docker.pkg.dev/mystic-tempo-416400/leare/apigateway-leare-gateway:gcp
#        docker push northamerica-northeast1-docker.pkg.dev/mystic-tempo-416400/leare/apigateway-leare-gateway:gcp


    - name: Deploy to VM
      uses: ./.github/workflows/deploy.yaml
      with:
        vm-name: ${{ secrets.VM_NAME }}
  